### ISSUE TITLE
Deploy with docker compose and similar setup vespa to other vector dbs

### ISSUE THREAD

**Issue by ricoms** [vespa-engine/pyvespa#658]
Hi. I'm developing a multi-vectordb load test benchmark, and I stumbled upon Vespa as an interesting candidate to be tested against.

I've already did that to ChromaDB, PgVector, and Redis. And I'll be doing that for other vector stores as well.

I was able to raise a Vespa container with docker compose like in the documentation, it was pretty easy:
```
vespa:
    image: vespaengine/vespa:8.282.24
    volumes:
      - vespa_persist:/opt/vespa/var
      - vespa_persist:/opt/vespa/logs
    env_file: vespa.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://vespa:19071/state/v1/health || exit 1"]
      interval: 5s
      start_period: 30s
      timeout: 10s
      retries: 3
```

And now I'm trying to implement a Vespa client using pyvespa, which inserts embeddings and then searches for embeddings. This client will be used by Locust (framework) user. Although, reading the pyvespa documentation I see a lot of Docker and deploy how tos, and very little about using an existing deploy that is not yet configured with a Schema.

Other vector DBs offer a way with simple configuration files to create an init script to create tables, indexes, schemas. And environment variables to setup overall configurations. I see that with pyvespa you dedicated time to create the Docker deploy, and even the docker python package is an obligatory requirement. Although I don't see that as a common use case as it's so easy to deploy it using common well known tools like docker compose, or docker.

Just to get things clear, setting up embeddings and rankings looks great as a very personalizable for multiple use cases. And I would like to use those. Although a simple use case, a client to setup an schema, insert embeddings and search embeddings is getting quite hard to achieve.

Basically below is my use case. And now I'm implementing a Vespa client using pyvespa, and for that I'm having a hard time with the documentation.

```
version: '3.9'

services:
  locust-master:
    image: locust-vespa
    build:
      context: ../../
      dockerfile: Dockerfile
      args:
        - TEST_NAME=locust
        - VECTORDB_NAME=vespa
    volumes:
      - ${PWD}/reports/vespa/locust_report:/opt/locust_report/
      - ${PWD}/config/:/opt/config/
    command: locust --config ${LOCUST_MASTER_CONFIG} ${LOCUST_USER_CLASSES}
    env_file: vespa.env
    depends_on:
      vespa:
        condition: service_healthy

  locust-worker:
    image: locust-vespa
    volumes:
      - ${PWD}/config/:/opt/config/
    command: locust --config /opt/config/worker.conf ${LOCUST_USER_CLASSES}
    env_file: vespa.env
    depends_on:
      vespa:
        condition: service_healthy

  vespa:
    image: vespaengine/vespa:8.282.24
    volumes:
      - vespa_persist:/opt/vespa/var
      - vespa_persist:/opt/vespa/logs
    env_file: vespa.env
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://vespa:19071/state/v1/health || exit 1"]
      interval: 5s
      start_period: 30s
      timeout: 10s
      retries: 3

volumes:
  vespa_persist:
    driver: local
  vespa_logs:
    driver: local
```

I'm trying to reverse engineer your VespaDocker implementation to try to understand if it's using configuration files or something similar, so I could set that up by myself. Is there somewhere something easier for me to follow?
